package resource

const (
	ChannelStable = "stable"
	ChannelDev    = "dev"
)

// Channel represents the latest Dart version available
// for download, generated by Dart's Buildbot.
type Channel struct {
	Channel  string `json:"channel" meddler:"build_channel"`
	Revision int64  `json:"revision" meddler:"build_sdk_revision"`
	Version  string `json:"version"  meddler:"build_sdk"`
}
